version: 1
update_configs:
  - package_manager: python
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    commit_message:
      prefix: "[requirements]"
      include_scope: true